name: hudsonstudy
description: A new Flutter project.


publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  #icon of google
  font_awesome_flutter: ^9.0.0

  #provider
  provider: ^4.3.2+2

  #google sign in
  firebase_auth: ^1.1.3
  google_sign_in: ^4.5.6

  #cloud firestore
  cloud_firestore: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/background1.jpg
    - assets/background2.png
    - assets/background3.jpg
    - assets/background4.jpg
    - assets/title.png
    - assets/user.png
    - assets/studyDefaultImage.png
    - assets/gradation1.png

